
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 05 00:12:36 EEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 43;
  public static final int LBRACKET = 10;
  public static final int UMINUS = 26;
  public static final int NOT_EQUAL = 18;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 8;
  public static final int GREATER = 13;
  public static final int LESS = 15;
  public static final int MINUS = 25;
  public static final int RPAREN = 9;
  public static final int NOT = 19;
  public static final int SEMICOLON = 31;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 30;
  public static final int CLASS = 40;
  public static final int PLUS = 24;
  public static final int ASSIGN = 20;
  public static final int IF = 27;
  public static final int THIS = 3;
  public static final int DOT = 29;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 17;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int NULL = 4;
  public static final int NUMBER = 37;
  public static final int MOD = 23;
  public static final int BREAK = 35;
  public static final int VOID = 39;
  public static final int EQ = 12;
  public static final int TIMES = 21;
  public static final int ELSE = 28;
  public static final int WHILE = 7;
  public static final int LESS_EQ = 16;
  public static final int STRING = 38;
  public static final int DOUBLE_LITERAL = 42;
  public static final int DIVISION = 22;
  public static final int DO = 6;
  public static final int INTEGER_LITERAL = 41;
  public static final int IDENTIFIER = 2;
  public static final int GREATER_EQ = 14;
}

