
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 03 18:09:47 EEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int SEMICOLON = 6;
  public static final int PLUS = 10;
  public static final int RPAREN = 5;
  public static final int EQUAL = 17;
  public static final int WHILE = 21;
  public static final int NOTEQUAL = 18;
  public static final int DIVISION = 9;
  public static final int IDENTIFIER = 2;
  public static final int GREATEREQUALTHAN = 15;
  public static final int LBRACKET = 19;
  public static final int LPAREN = 4;
  public static final int RBRACKET = 20;
  public static final int STRING_LITERAL = 24;
  public static final int LESSTHAN = 14;
  public static final int EOF = 0;
  public static final int MINUS = 11;
  public static final int PRINT = 3;
  public static final int error = 1;
  public static final int ASSIGN = 7;
  public static final int LESSEQUALTHAN = 16;
  public static final int INTEGER_LITERAL = 22;
  public static final int GREATERTHAN = 13;
  public static final int DOUBLE_LITERAL = 23;
  public static final int UMINUS = 12;
}

