
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 21 15:37:23 EET 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 11;
  public static final int DOUBLE_LITERAL = 14;
  public static final int UMINUS = 12;
  public static final int STRING_LITERAL = 15;
  public static final int PLUS = 10;
  public static final int EOF = 0;
  public static final int EQ = 7;
  public static final int error = 1;
  public static final int DIVISION = 9;
  public static final int PRINT = 3;
  public static final int RPAREN = 5;
  public static final int SEMICOLON = 6;
  public static final int TIMES = 8;
  public static final int IDENTIFIER = 2;
  public static final int LPAREN = 4;
  public static final int INTEGER_LITERAL = 13;
}

